package com.springbootcamp.springsecurity.entity;


public enum TO_STATUS{

    CANCELLED(1, FROM_STATUS.ORDER_PLACED),
    ORDER_CONFIRMED(2,FROM_STATUS.ORDER_PLACED),
    ORDER_REJECTED(3,FROM_STATUS.ORDER_PLACED),
    REFUND_INITIATED(4,FROM_STATUS.CANCELLED),
    CLOSED(5,FROM_STATUS.CANCELLED),
    REFUND_INITIATED_ORDER_REJECTED(6,FROM_STATUS.ORDER_REJECTED),
    CLOSED_ORDER_REJECTED(7,FROM_STATUS.ORDER_REJECTED),
    CANCELLED_ORDER_CONFIRMED(8,FROM_STATUS.ORDER_CONFIRMED),
    ORDER_SHIPPED(9,FROM_STATUS.ORDER_CONFIRMED),
    DELIVERED(10,FROM_STATUS.ORDER_SHIPPED),
    RETURN_REQUESTED(11,FROM_STATUS.DELIVERED),
    CLOSED_DELIVERED(12,FROM_STATUS.DELIVERED),
    RETURN_REJECTED(13,FROM_STATUS.RETURN_REQUESTED),
    RETURN_APPROVED(14,FROM_STATUS.RETURN_REQUESTED),
    CLOSED_RETURN_REJECTED(15,FROM_STATUS.RETURN_REJECTED),
    PICK_UP_INITIATED(16,FROM_STATUS.RETURN_APPROVED),
    PICK_UP_COMPLETED(17,FROM_STATUS.PICK_UP_INITIATED),
    REFUND_INITIATED_PICK_UP_COMPLETE(18,FROM_STATUS.PICK_UP_COMPLETED),
    REFUND_COMPLETED(19,FROM_STATUS.REFUND_INITIATED),
    CLOSED_REFUND_COMPLETED(20,FROM_STATUS.REFUND_COMPLETED);


    TO_STATUS(int i, FROM_STATUS orderPlaced) {
    }
}